const questions=[
{q:"Saya dapat menjelaskan makna Pancasila sebagai kepribadian bangsa dengan bahasa sendiri.",options:[["Belum, saya masih membutuhkan contoh dan penjelasan.",0],["Sebagian, saya memahami konsep dasarnya.",1],["Ya, saya dapat menjelaskan dan memberi contoh.",2]]},
{q:"Ketika melihat masalah di sekolah, saya dapat menghubungkannya dengan nilai Pancasila.",options:[["Saya masih kesulitan menentukan nilai yang sesuai.",0],["Saya dapat menentukan nilai dengan sedikit bantuan.",1],["Saya dapat menganalisis hubungan masalah dan nilai Pancasila.",2]]},
{q:"Saat menemukan pendapat berbeda dalam kelompok, saya mampu menentukan sikap yang tepat.",options:[["Saya masih membutuhkan arahan.",0],["Saya dapat menentukan sikap setelah berdiskusi.",1],["Saya dapat memberi alasan dan solusi secara mandiri.",2]]},
{q:"Saya nyaman belajar melalui contoh kasus nyata di lingkungan sekolah.",options:[["Saya lebih mudah belajar jika ada contoh sederhana lebih dulu.",0],["Saya cukup nyaman dengan kasus yang terarah.",1],["Saya siap menganalisis kasus yang lebih kompleks.",2]]},
{q:"Saya dapat menyusun solusi terhadap masalah yang berkaitan dengan penerapan nilai Pancasila.",options:[["Belum, saya membutuhkan panduan langkah demi langkah.",0],["Saya dapat menyusun solusi dengan bantuan pertanyaan penuntun.",1],["Saya dapat menyusun dan mengevaluasi beberapa alternatif solusi.",2]]},
{q:"Saya mampu merefleksikan tindakan saya dan menghubungkannya dengan nilai Pancasila.",options:[["Saya masih memerlukan contoh pertanyaan refleksi.",0],["Saya dapat merefleksi dengan panduan.",1],["Saya dapat merefleksi dan merumuskan tindakan perbaikan.",2]]}
];
let current=0,answers=new Array(questions.length).fill(null);const quizBox=document.getElementById("quizBox"),nextBtn=document.getElementById("nextBtn"),prevBtn=document.getElementById("prevBtn"),progressBar=document.getElementById("progressBar"),resultBox=document.getElementById("resultBox");
function renderQuestion(){const item=questions[current];progressBar.style.width=`${((current+1)/questions.length)*100}%`;quizBox.innerHTML=`<div class="question-num">Pertanyaan ${current+1} dari ${questions.length}</div><div class="question-title">${item.q}</div><div class="options">${item.options.map(opt=>`<label class="option"><input type="radio" name="answer" value="${opt[1]}" ${answers[current]===opt[1]?"checked":""}><span>${opt[0]}</span></label>`).join("")}</div>`;prevBtn.disabled=current===0;nextBtn.textContent=current===questions.length-1?"Lihat Hasil":"Berikutnya";document.querySelectorAll('input[name="answer"]').forEach(r=>r.addEventListener("change",()=>answers[current]=Number(r.value)))}
nextBtn.addEventListener("click",()=>{if(answers[current]===null){alert("Pilih satu jawaban terlebih dahulu.");return}if(current<questions.length-1){current++;renderQuestion()}else showResult()});prevBtn.addEventListener("click",()=>{if(current>0){current--;renderQuestion()}});
function routeFromScore(score){if(score<=4)return["eksplorasi","Jalur Eksplorasi","Aku Butuh Panduan","🟢"];if(score<=8)return["penguatan","Jalur Penguatan","Aku Siap Menganalisis","🔵"];return["tantangan","Jalur Tantangan","Aku Siap Memecahkan Masalah","🟣"]}
function showResult(){const score=answers.reduce((a,b)=>a+b,0),[id,label,title,icon]=routeFromScore(score);localStorage.setItem("pancapath_score",score);localStorage.setItem("pancapath_route",id);resultBox.classList.remove("hidden");resultBox.innerHTML=`<div class="question-num" style="color:#93c5fd">Hasil Cek Kesiapan</div><h3>${icon} ${label}</h3><p><strong>${title}</strong></p><p>Hasil ini menunjukkan titik awal yang disarankan, bukan label kemampuan. Kamu dapat berpindah jalur setelah menyelesaikan checkpoint.</p><button class="btn primary" onclick="openPath('${id}')">Mulai Jalur Belajarku</button>`;resultBox.scrollIntoView({behavior:"smooth",block:"center"})}
const pathData={
 eksplorasi:{label:"Jalur Eksplorasi",title:"Aku Butuh Panduan",intro:"Mulai dari contoh konkret, visual, dan bantuan bertahap.",color:"🟢",missions:[["Misi 1 — Kenali Konsep","Pancasila sebagai kepribadian bangsa berarti nilai-nilai Pancasila tercermin dalam cara berpikir, bersikap, dan bertindak dalam kehidupan sehari-hari."],["Misi 2 — Lihat Contoh","Contoh: gotong royong membersihkan kelas, menghargai pendapat, membantu teman, dan menaati kesepakatan bersama."],["Misi 3 — Scaffolding","Gunakan pertanyaan penuntun: Apa yang terjadi? Siapa yang terlibat? Nilai Pancasila apa yang tampak? Apa tindakan yang sebaiknya dilakukan?"],["Misi 4 — Latihan","Pilih satu pengalaman di kelas dan tuliskan nilai Pancasila yang paling sesuai."]],checkpoint:{q:"Sekelompok siswa membersihkan kelas bersama tanpa membedakan teman. Nilai yang paling tampak adalah...",options:[["Gotong royong dan persatuan",true],["Persaingan antarkelompok",false],["Mendahulukan kepentingan pribadi",false]]}},
 penguatan:{label:"Jalur Penguatan",title:"Aku Siap Menganalisis",intro:"Kuatkan pemahaman melalui kasus kontekstual dan analisis.",color:"🔵",missions:[["Misi 1 — Baca Kasus","Dalam kerja kelompok, beberapa siswa hanya ingin bekerja dengan teman dekatnya dan mengabaikan pendapat anggota lain."],["Misi 2 — Analisis Masalah","Identifikasi perilaku yang terjadi, nilai Pancasila yang belum diterapkan, dan dampaknya terhadap kelompok."],["Misi 3 — Rancang Solusi","Susun solusi agar semua anggota kelompok mendapat ruang berpendapat."],["Misi 4 — Diskusi","Bandingkan solusi dengan teman dan perbaiki alasanmu berdasarkan masukan."]],checkpoint:{q:"Solusi yang paling sesuai dengan nilai Pancasila pada kasus tersebut adalah...",options:[["Membuat kesepakatan agar setiap anggota memperoleh giliran menyampaikan pendapat",true],["Membiarkan anggota dominan memimpin semua keputusan",false],["Memisahkan siswa yang berbeda pendapat",false]]}},
 tantangan:{label:"Jalur Tantangan",title:"Aku Siap Memecahkan Masalah",intro:"Evaluasi alternatif tindakan dan rumuskan solusi yang dapat dipertanggungjawabkan.",color:"🟣",missions:[["Civic Challenge","Di media sosial muncul konten yang merendahkan budaya daerah dan menganggap budaya lokal tidak relevan bagi generasi muda."],["Misi 1 — Evaluasi","Tentukan dampak konten tersebut terhadap jati diri bangsa dan kehidupan bersama."],["Misi 2 — Bandingkan Solusi","Bandingkan minimal dua alternatif: edukasi digital, kampanye budaya, dialog, atau pelaporan konten."],["Misi 3 — Buat Produk Mini","Susun satu paragraf argumentasi, mini-infografis, atau rancangan kampanye digital yang mempromosikan nilai Pancasila."]],checkpoint:{q:"Tindakan paling kuat untuk menunjukkan Pancasila sebagai kepribadian bangsa adalah...",options:[["Mengembangkan respons kritis yang menghargai budaya sendiri sekaligus tetap terbuka terhadap budaya lain",true],["Menolak semua budaya asing tanpa pertimbangan",false],["Membiarkan konten karena tidak berkaitan dengan kehidupan sekolah",false]]}}
};
function openPath(id){const d=pathData[id];document.getElementById("jalur").classList.add("hidden");const section=document.getElementById("ruangBelajar");section.classList.remove("hidden");section.scrollIntoView({behavior:"smooth"});document.getElementById("pathContent").innerHTML=`<div class="learning-shell"><aside class="learning-sidebar"><span class="badge">${d.color} ${d.label}</span><h2>${d.title}</h2><p>${d.intro}</p><hr style="border:0;border-top:1px solid #e6eaf0;margin:22px 0"><strong>Target belajar</strong><p style="color:#667085">Selesaikan semua misi lalu kerjakan checkpoint.</p></aside><div class="learning-main"><span class="eyebrow">Ruang Belajar</span><h2>${d.label}</h2>${d.missions.map(m=>`<div class="mission"><h4>${m[0]}</h4><p>${m[1]}</p></div>`).join("")}<div class="checkpoint"><strong>Checkpoint</strong><p>${d.checkpoint.q}</p><div class="choice-row">${d.checkpoint.options.map(o=>`<button class="choice-btn" data-correct="${o[1]}">${o[0]}</button>`).join("")}</div><div class="feedback"></div></div></div></div>`;document.querySelectorAll(".choice-btn").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".choice-btn").forEach(x=>x.disabled=true);const correct=btn.dataset.correct==="true";btn.classList.add(correct?"correct":"wrong");const feedback=btn.parentElement.nextElementSibling;if(correct){feedback.textContent="✅ Tepat. Kamu siap melanjutkan ke refleksi.";feedback.style.color="#15803d"}else{feedback.textContent="🔎 Belum tepat. Tinjau kembali misi dan diskusikan alasanmu.";feedback.style.color="#b91c1c";document.querySelectorAll(".choice-btn").forEach(x=>{if(x.dataset.correct==="true")x.classList.add("correct")})}}))}window.openPath=openPath;
document.querySelectorAll("[data-open]").forEach(btn=>btn.addEventListener("click",()=>openPath(btn.dataset.open)));document.getElementById("closePath").addEventListener("click",()=>{document.getElementById("ruangBelajar").classList.add("hidden");document.getElementById("jalur").classList.remove("hidden");document.getElementById("jalur").scrollIntoView({behavior:"smooth"})});
document.getElementById("reflectionForm").addEventListener("submit",e=>{e.preventDefault();const data={pengetahuan:document.getElementById("ref1").value,tantangan:document.getElementById("ref2").value,tindakan:document.getElementById("ref3").value,saved_at:new Date().toISOString()};localStorage.setItem("pancapath_reflection",JSON.stringify(data));document.getElementById("saveNote").textContent="Refleksi tersimpan di perangkat ini."});const saved=localStorage.getItem("pancapath_reflection");if(saved){try{const d=JSON.parse(saved);document.getElementById("ref1").value=d.pengetahuan||"";document.getElementById("ref2").value=d.tantangan||"";document.getElementById("ref3").value=d.tindakan||""}catch(e){}}document.getElementById("menuBtn").addEventListener("click",()=>document.querySelector(".nav").classList.toggle("open"));document.querySelectorAll(".nav a").forEach(a=>a.addEventListener("click",()=>document.querySelector(".nav").classList.remove("open")));renderQuestion();
